# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#   Convert a hash of Chronos options to a structure for create_resources function
#
Puppet::Functions.create_function(:'chronos::chronos_options') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    structure = {}
    args.each do |options|
      raise Puppet::ParseError, "chronos_options() Options should be provided as a Hash! Got: #{options.inspect}" unless options.is_a? Hash
      options.each do |key, value|
        next unless key && !value.nil?
        structure[key] = {}
        structure[key]['value'] = value
      end
    end
    structure
  
  end
end
